name: MSO_E5_Dev_AutoRenew

on:
  workflow_dispatch: # Execução manual
  schedule:
    - cron: '0 3 * * *' # Executa todo dia às 3h UTC
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  watch:
    types: [started]

jobs:
  build:
    name: Build and call API
    runs-on: ubuntu-latest
    if: (github.event.repository.owner.id == github.event.sender.id) || 
        github.event_name == 'workflow_dispatch' || 
        github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true

      - name: Install dependencies
        run: |
          pip install requests

      - name: Call API
        env:
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo "$(date +"%Y-%m-%d %H:%M:%S") begin" > time.log
          python3 main.py

      - name: Commit refresh token
        run: |
          git config --global user.email "Harryjjjjved@gmail.com"
          git config --global user.name "Harry"
          git add .
          git commit -m "Update new refresh token with MSO_E5_Dev_AutoRenew" -a || echo "No changes to commit"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
